// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package store

import (
	"database/sql"

	"github.com/google/uuid"
)

type List struct {
	ListID   uuid.UUID
	ListName string
}

type Notification struct {
	NotificationID   uuid.UUID
	NotificationName sql.NullString
	Html             sql.NullString
}

type Subscriber struct {
	SubscribedID uuid.UUID
	Email        string
	IsSubscribed sql.NullBool
}
